# Generated by Django 5.0.4 on 2024-06-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'non_field_errors': 'Пользователь с этим логином или именем уже существует!'}, max_length=32, unique=True),
        ),
    ]
