# Generated by Django 5.0.4 on 2024-06-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': {'non_field_errors': 'Пользователь с этим логином или именем уже существует!'}}, max_length=32, unique=True),
        ),
    ]
