# Generated by Django 5.0.4 on 2024-05-27 06:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infobooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umn', models.CharField(max_length=32)),
                ('uen', models.CharField(max_length=32)),
                ('utn', models.CharField(max_length=32)),
                ('ubdn', models.CharField(max_length=32)),
                ('ubpn', models.CharField(max_length=32)),
                ('supply_contract', models.TextField(max_length=32)),
                ('ship_date', models.DateTimeField(default=datetime.date.today)),
                ('consignee', models.TextField()),
                ('adress', models.TextField()),
                ('equipment', models.TextField()),
                ('bridge_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_design', to='infobooks.infobook')),
                ('bridge_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_pattern', to='infobooks.infobook')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine', to='infobooks.infobook')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='infobooks.infobook')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to=settings.AUTH_USER_MODEL)),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmission', to='infobooks.infobook')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('operating_time', models.IntegerField()),
                ('order_number', models.TextField()),
                ('order_date', models.DateTimeField()),
                ('organization', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_service', to='machine.machine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_service', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_type', to='infobooks.infobook')),
            ],
        ),
    ]
