# Generated by Django 5.0.4 on 2024-05-28 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobooks', '0001_initial'),
        ('machine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disorder_date', models.DateTimeField()),
                ('operating_time', models.IntegerField()),
                ('description', models.TextField()),
                ('additional_parts', models.TextField()),
                ('wasted_time', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_complaint', to='machine.machine')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_method', to='infobooks.infobook')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_node', to='infobooks.infobook')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
