# Generated by Django 5.0.4 on 2024-05-29 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobooks', '0001_initial'),
        ('machine', '0002_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='bridge_design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bridge_design', to='infobooks.infobook'),
        ),
    ]
