# Generated by Django 5.0.4 on 2024-05-29 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobooks', '0001_initial'),
        ('machine', '0005_alter_machine_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='bridge_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_design', to='infobooks.infobook'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='bridge_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_pattern', to='infobooks.infobook'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
