# Generated by Django 5.0.4 on 2024-05-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_alter_machine_bridge_design_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='ship_date',
            field=models.DateTimeField(),
        ),
    ]
